# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a119f0d75023a5be82463995281621b263092e195909c3acea6d0e52920638e2d2d28ab802823867472a3a85dcfea83a9ad9b26ec7e8e266c48b8e6cf26b92e

test:
  secret_key_base: 9a2eeb141161d55e5ed29b56fd8915308bb033075f0db38687878546940aa3ccb637d4905868a92e21d6965e1218b92540f3fc2150ccee0bb75c2366c07df90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
